### ISSUE TITLE
Could not reach Kong on http://kong:8001

### ISSUE THREAD

**Issue by hanwenbo** [PGBI/kong-dashboard#141]
kong-dashboard start --kong-url http://kong:8001
Connecting to Kong on http://kong:8001 ...
Could not reach Kong on http://kong:8001
Error details:
{ Error: getaddrinfo ENOTFOUND kong kong:8001
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'kong',
  host: 'kong',
  port: '8001' }

**Comment by hanwenbo** [comment]
kong-dashboard start --kong-url http://localhost:8001
