### ISSUE TITLE
UnhandledPromiseRejectionWarning when running with Kong "rcX" version strings.

### ISSUE THREAD

**Issue by cjfudge** [PGBI/kong-dashboard#169]
Kong-dashboard is not compatible with release candidate kong versions (e.g. 0.14.0rc1).
It appears that the version parser cannot handle the additional "rc*" suffix .

* Kong version = 0.14.0rc1
* Kong Dashboard version = 3.3.0
* Node version = 9.4.0
* Npm version = 5.6.0

Output when starting up:

```
Connecting to Kong on http://localhost:8001 ...
(node:20607) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 0.14.0rc1
    at new SemVer (/root/.nvm/versions/node/v9.4.0/lib/node_modules/kong-dashboard/node_modules/semver/semver.js:305:11)
    at compare (/root/.nvm/versions/node/v9.4.0/lib/node_modules/kong-dashboard/node_modules/semver/semver.js:578:10)
    at Function.lt (/root/.nvm/versions/node/v9.4.0/lib/node_modules/kong-dashboard/node_modules/semver/semver.js:612:10)
    at request.get.then.then (/root/.nvm/versions/node/v9.4.0/lib/node_modules/kong-dashboard/bin/kong-dashboard.js:161:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by heamaral** [comment]
+1

**Comment by guowushi** [comment]
+1
