### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 1.0.0rc3

### ISSUE THREAD

**Issue by xumengsi** [PGBI/kong-dashboard#190]
(node:13040) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 1.0.0rc3
    at new SemVer (C:\Users\xumengsi\AppData\Roaming\npm\node_modules\kong-dashboard\node_modules\semver\semver.js:312:11)
    at compare (C:\Users\xumengsi\AppData\Roaming\npm\node_modules\kong-dashboard\node_modules\semver\semver.js:585:10)
    at Function.lt (C:\Users\xumengsi\AppData\Roaming\npm\node_modules\kong-dashboard\node_modules\semver\semver.js:619:10)
    at request.get.then.then (C:\Users\xumengsi\AppData\Roaming\npm\node_modules\kong-dashboard\bin\kong-dashboard.js:161:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dragon9783** [comment]
Same issue to me, maybe kong-dashboard latest image not support kong version 1.0.0rc3.

**Comment by Sherlock-Holo** [comment]
I got this

> (node:6) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: 1.0.0rc4                                         
>     at new SemVer (/app/node_modules/semver/semver.js:293:11)                                                           
>     at compare (/app/node_modules/semver/semver.js:566:10)                                                              
>     at Function.lt (/app/node_modules/semver/semver.js:600:10)                                                          
>     at request.get.then.then (/app/bin/kong-dashboard.js:161:16)                                                        
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
> of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id
> : 1)
> (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections th
> at are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by illyaMs** [comment]
Should be the same issue as https://github.com/PGBI/kong-dashboard/issues/194
