### ISSUE TITLE
`node ./bin/kong-dashboard build` fails on Windows 10

### ISSUE THREAD

**Issue by allenmoatallen** [PGBI/kong-dashboard#20]
With latest node and npm versions installed the install fails on `node ./bin/kong-dashboard build`.

Log:

```
48683 silly lifecycle kong-dashboard@1.1.0~install: Args: [ '/d /s /c', 'node ./bin/kong-dashboard build' ]
48684 silly lifecycle kong-dashboard@1.1.0~install: Returned: code: 1  signal: null
48685 info lifecycle kong-dashboard@1.1.0~install: Failed to exec install script
48686 verbose unlock done using C:\Users\<USER>\AppData\Roaming\npm-cache\_locks\staging-952186523723db65.lock for C:\Users\<USER>\AppData\Roaming\npm\node_modules\.staging
48687 silly rollbackFailedOptional Starting
48688 silly rollbackFailedOptional Finishing
48689 silly runTopLevelLifecycles Starting
48690 silly runTopLevelLifecycles Finishing
48691 silly install printInstalled
48692 verbose stack Error: kong-dashboard@1.1.0 install: `node ./bin/kong-dashboard build`
48692 verbose stack Exit status 1
48692 verbose stack     at EventEmitter.<anonymous> (C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
48692 verbose stack     at emitTwo (events.js:87:13)
48692 verbose stack     at EventEmitter.emit (events.js:172:7)
48692 verbose stack     at ChildProcess.<anonymous> (C:\Users\<USER>\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
48692 verbose stack     at emitTwo (events.js:87:13)
48692 verbose stack     at ChildProcess.emit (events.js:172:7)
48692 verbose stack     at maybeClose (internal/child_process.js:818:16)
48692 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by PGBI** [comment]
Not sure what the issue you specifically have is, the output above just says kong-dashboard build returned 1 (a failure).

Can you please include the content of the entire npm-debug.log file?

**Comment by arsdehnel** [comment]
I'm running on an Amazon Linux EC2 instance and hitting the same error.  Attached is the npm-debug.log (renamed to .txt so github would allow the upload) from that error on my machine.  
[npm-debug.txt](https://github.com/PGBI/kong-dashboard/files/263515/npm-debug.txt)

**Comment by nimboya** [comment]
@arsdehnel  Is this a Windows or a linux instance. Are you sure you have the permissions set right too? Also ensure bower, npm and node are properly installed. Revert

**Comment by PGBI** [comment]
Closing as you don't need to build kong-dashboard to use it anymore. Npm package ships with the app already built.
