### ISSUE TITLE
Npm install failing after cloning from source

### ISSUE THREAD

**Issue by w0w** [PGBI/kong-dashboard#68]
`$ npm install`

> node-sass@4.1.1 install /opt/kong-dashboard/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/ubuntu/.npm/node-sass/4.1.1/linux-x64-46_binding.node

> node-sass@4.1.1 postinstall /opt/kong-dashboard/node_modules/node-sass
> node scripts/build.js

Binary found at /opt/kong-dashboard/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine

> kong-dashboard@1.2.1 install /opt/kong-dashboard
> node ./bin/kong-dashboard build

Generating css files
Generating js files...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './node_modules/jquery/dist/jquery.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at addFile (/opt/kong-dashboard/node_modules/uglify-js/tools/node.js:70:22)
    at /opt/kong-dashboard/node_modules/uglify-js/tools/node.js:81:17
    at Array.forEach (native)
    at Object.exports.minify (/opt/kong-dashboard/node_modules/uglify-js/tools/node.js:79:26)
    at /opt/kong-dashboard/lib/kong-dashboard.js:85:32
    at f (/opt/kong-dashboard/node_modules/glob/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/opt/kong-dashboard/node_modules/glob/glob.js:151:7)

**Comment by PGBI** [comment]
what's your npm version?

**Comment by w0w** [comment]
2.14.7

**Comment by PGBI** [comment]
Should be fixed with kong-dashboard v1.3.0
