### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by dinymis** [PGBI/kong-dashboard#94]
npm start
> kong-dashboard@2.0.0 start /home/dy/kong/kong-dashboard
> node ./bin/kong-dashboard start
Launching webserver
/home/dy/kong/kong-dashboard/lib/server.js:24
webapp.use(function *(next){               
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
Proxy server is down.

**Comment by Jamesking56** [comment]
+1

**Comment by arsdehnel** [comment]
what version of node are you running?
